version: '{branch}.{build}'
image: Visual Studio 2017
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Installrepo specifig stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./Logging/Logging.csproj --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish ./Logging/Logging.csproj
after_build:
  # For once the build has completed
artifacts:
 - path: '\Logging\bin\Debug\netstandard2.0\publish'
   name: Affecto.Logging
   type: NugetPackage
clone_depth: 1
test_script:
  # restore packages for our unit tests
  #- cmd: dotnet restore ./tests/tests.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  #- cmd: cd tests
  #- cmd: dotnet xunit
on_finish :
  # any cleanup in here
deploy: off

pull_requests:
  do_not_increment_build_number: true
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
configuration: Release
deploy:
- provider: NuGet
  api_key:
    secure: ySttUuKXaqz/qn7dZRtJJs7H8wTDgT8Wgi55QFGZjmVE2XL14T2puaPiBcNMZC1l
  on:
    APPVEYOR_REPO_TAG: true